### ISSUE TITLE
Blank white banner on iPad when in landscape mode

### ISSUE THREAD

**Issue by zanemcca** [BranchMetrics/smart-app-banner-branch-deep-linking-web-library#331]
The banner is showing up without having any styling or content when in landscape. It seems fine on the iPhone but it happens every time on my iPad. ![](http://i.imgur.com/x10wBhC.jpg)

**Comment by aaustin** [comment]
Same here - that's very peculiar..

**Comment by jsaleigh** [comment]
@zanemcca This appears to be caused by the `style="margin-top: 76px"` attribute on the body tag.  It looks like you are using this to push all content below the smart banner iframe, however that is causing the iPad to believe that nothing above the 76px line is renderable.  Hope this helps!

**Comment by jsaleigh** [comment]
My apologies @zanemcca!  I believe that styling is from our banner code, although I'm not sure why the behavior you're seeing doesn't occur in other places.  I'm digging into that now.

**Comment by jsaleigh** [comment]
Ok, I think I found it for real this time :)

In this file: http://instanews.com/styles/main.css

There is this chunk of css:
```
@media (orientation:landscape) {
    .platform-ios.platform-browser.platform-ipad {
        position: fixed
    }
}
```

That, combined with the `margin-top` on the body, is causing the issue, from what I can tell.

When I remove the `position: fixed` style in testing, the problem seems to go away.  I don't see anything that could actually use that, so I can't tell what that would break.

**Comment by zanemcca** [comment]
@jsaleigh Thanks for hunting that down. 

It is part of Ionic's code and it looks like it has to do with fixing the header in Safari for iOS 7+. I am not sure what exactly that entails but I don't think it is your problem.
